index:
  path: /
  controller: App\Controller\LoginController::index
  methods: ['POST','GET']
authentication_token:
  path: /authentication_token
  methods: ['POST']

login:
  path: /login
  controller: App\Controller\LoginController::index
  methods: ['POST','GET']

Registration:
    path: /register
    controller: App\Controller\RegistrationController::index
    methods: [ 'POST','GET' ]
logout :
  path: /logout
  controller: App\Controller\LoginController::logout
  methods: [ 'GET' ]
users:
  path: /users
  controller: App\Controller\UsersController::getUsers
  methods: ['GET']
activate:
  path: /activate
  controller: App\Controller\UsersController::verifyUser
  methods: [ 'GET','POST','PUT' ]
disactivate:
  path: /disactivate
  controller: App\Controller\UsersController::disactivate
  methods: [ 'GET','POST' ]
posting:
  path: /posting
  controller: App\Controller\PostController::index
  methods: ['GET','POST']
getUse:
  path: /getUser
  controller: App\Controller\PostController::getUse
  methods: ['GET','POST']
getPost:
  path: /getPost
  controller: App\Controller\CommentContoller::getPost
  methods: ['GET','POST']
Comment:
  path: /Comment
  controller: App\Controller\CommentContoller::create
  methods: ['POST']
ListingP:
  path: /ListingPosts
  controller: App\Controller\ListingPostsController::ListingPosts
  methods: ['POST','GET']
ListingC:
  path: /ListingComments
  controller: App\Controller\AffichageCommentaires::ListingComments
  methods: ['POST','GET']
ContactUs:
  path: /ContactUs
  controller: App\Controller\ContactUsController::Contact
  methods: ['Post']
like:
  path: /like
  controller: App\Controller\PostController::likepost
  methods: [ 'Post','Get' ]
updateP:
  path: /UpdateP
  controller: App\Controller\updateController::updatePost
  methods: [ 'POST','GET' ]
updateC:
  path: /UpdateC
  controller: App\Controller\updateController::updateComment
  methods: [ 'POST','GET' ]
deleteP:
  path: /DeleteP
  controller:  App\Controller\deleteController::DeletePost
  methods: ['POST','GET']
deleteC:
  path: /DeleteC
  controller:  App\Controller\deleteController::DeleteComment
  methods: ['POST','GET']
getLikePosts:
  path: /getLikePosts
  controller:  App\Controller\PostController::getlikePosts
  methods: ['GET']
searchPU:
  path:  /SearchPostsbyusername
  controller:  App\Controller\searchController::searchPostbyusername 
  methods: ['GET']
searchPC:
  path:  /SearchPostsbycategory
  controller:  App\Controller\searchController::searchPostbycategory
  methods: ['GET']
searchPD:
  path:  /SearchPostsbydescription
  controller:  App\Controller\searchController::searchPostbydescription
  methods: ['GET']
